### ISSUE TITLE
JSONRPCKit Pod as dependency. 

### ISSUE THREAD

**Issue by ghost** [bricklife/JSONRPCKit#10]
I'm using a JSONRPCKit as a Pod in my Framework:

`pod 'JSONRPCKit', :git=> 'https://github.com/bricklife/JSONRPCKit.git'`

But I'm not able to add it to my `.podspec`: 

`s.dependency 'JSONRPCKit'`

When I try to validate `.podspec`:

` - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for 'JSONRPCKit' depended upon by 'MyFramework') during validation.`

Is it possible to add JSONRPCKit to my .podspec?  

Thank you!
@bricklife , @ishkawa , @SAMUKEI

**Comment by bricklife** [comment]
@Rokelis I'm sorry to have kept you waiting so long 🙇 Just pushed JSONRPCKit.podspec into CocoaPods repository. Please try again. Thanks.

**Comment by bricklife** [comment]
Maybe you can use two versions as follows:
- [2.0.3](https://github.com/bricklife/JSONRPCKit/tree/2.0.3) for Xcode 8 or 9
- [3.0.0](https://github.com/bricklife/JSONRPCKit/tree/3.0.0) for Xcode 9

**Comment by ghost** [comment]
@bricklife 
I get this error when calling `pod install`:
`[!] Unable to find a specification for 'JSONRPCKit' depended upon by 'MyProject'`

Podfile:
`pod 'JSONRPCKit', '~> 3.0.0'`

How should I add this kit as a pod?

**Comment by bricklife** [comment]
@Rokelis 
Could you try `pod update JSONRPCKit`?

**Comment by ghost** [comment]
@bricklife 
Everything works fine. 
Good job! 
Thanks!
