### ISSUE TITLE
Type 'ViewController.ServiceRequest<Batch>' does not conform to protocol 'Request'

### ISSUE THREAD

**Issue by jaymutzafi** [bricklife/JSONRPCKit#14]
Following the [updated example](https://github.com/bricklife/JSONRPCKit/blob/master/Example/Example/MathService.swift) I've set up a simple request:

`
struct ServiceRequest<Batch: JSONRPCKit.Batch>: APIKit.Request {
    let batch: Batch
    
    typealias Response = Batch.Responses
    
    var baseURL: URL {
        return URL(string: "https://someapi.com")!
    }
    
    var method: HTTPMethod {
        return .post
    }
    
    var path: String {
        return "/"
    }
    
    var parameters: Any? {
        return batch.requestObject
    }
    
    func response(from object: Any, urlResponse: HTTPURLResponse) throws -> Response {
        return try batch.responses(from: object)
    }
}
` 

But i keep getting the error "Type 'ViewController.ServiceRequest<Batch>' does not conform to protocol 'Request'". If I click fix it just adds `var method: HTTPMethod` but then complains that `var method: HTTPMethod {  return .post }` is an invalid redeclaration. 

I am importing APIKit & JSONRPCKit with no errors. 

Any idea what's wrong?

Thanks in advance.

**Comment by bricklife** [comment]
@jaymutzafi Do you use any other network library? If yes, please try the following code:

```swift
        var method: APIKit.HTTPMethod {
            return .post
        }
```

**Comment by jaymutzafi** [comment]
Thanks!

I am not sure if I am using anything else that it is confusing this for, but that did make the error disappear and now i get a new "/Frameworks/APIKit.framework: No such file or directory" under "Shell Script Invocation Error", so I guess installing APIKit didn't go quite right? (despite import APIKit not generating an error)

I tried using Carthage to install JSONRPCKit which seemed to include result but omit APIKit which I then tried installing separately but had to use cocoapods. Still trying to wrap my head around package managers.

**Comment by jaymutzafi** [comment]
I would like to try to re-add JSONRPCKit to a new project from scratch. 

1. Is there a (simple) way to manually add it?

2. If not, how do I add it together with Result and APIKit via Cocoapods? 

Thanks.

**Comment by bricklife** [comment]
@jaymutzafi 
I think using CocoaPods is the most simple way. Please try to put the following minimum Podfile into your project directory,
```
target 'YOUR_TARGET_HERE' do
  use_frameworks!
  pod 'APIKit'
  pod 'JSONRPCKit'
end
```

and then exec the following command:
```
$ pod update
```

See also: https://guides.cocoapods.org/using/using-cocoapods.html

**Comment by bricklife** [comment]
@jaymutzafi And also, could you tell me about your development environment? For instance, host OS, target OS, Xcode version, and etc.

**Comment by jaymutzafi** [comment]
Shouldn't I include pod 'Result' in there as well?

I am on OS X 10.13.2 building for iOS 11.2 in XCode 9.2 (9C40b)

After installing with above instructions on a brand new project i now get "Cannot load underlying module for 'APIKit'" on import APIKit

**Comment by bricklife** [comment]
@jaymutzafi Are you still having the problem? I saw the same message as attached just one, but I could build my target. Please try it!
<img width="1649" alt="screen shot 2018-01-23 at 11 59 21 am" src="https://user-images.githubusercontent.com/266357/35274741-2c8971c8-0035-11e8-9a86-b8369dfee97d.png">

**Comment by jaymutzafi** [comment]
@bricklife strange, it still showed the error but indeed ran fine when I built it. Seems to be working. 

Thanks!
