### ISSUE TITLE
Does JSONRPCKit support Swift Package Manager?

### ISSUE THREAD

**Issue by jerry-sl** [bricklife/JSONRPCKit#9]
Does JSONRPCKit support Swift Package Manager?

**Comment by danilaplee** [comment]
great question

**Comment by andyChuang** [comment]
Please support it. I really need it. Thank you!

**Comment by bricklife** [comment]
@jerry-sl @danilaplee @andyChuang I'm sorry to have kept you waiting so long 🙇 I'm working on Swift Package Manager support. It will be completed soon...!

**Comment by bricklife** [comment]
Just supported!
